[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "biblionix"
description = "Python client library to interface with Biblionix library systems"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
dependencies = [
    "httpx"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dynamic = [
    "version",
]

[[project.authors]]
name = "William Jackson"
email = "william@subtlecoolness.com"

[project.urls]
"Homepage" = "https://github.com/williamjacksn/python-biblionix"
"Changes" = "https://github.com/williamjacksn/python-biblionix/releases"
"Issues" = "https://github.com/williamjacksn/python-biblionix/issues"

[tool.setuptools.dynamic]
version.attr = "biblionix.__version__"
